### PR TITLE
reenable DV components theming

### PR DESCRIPTION
**Pull request by ChronosSF**
This should allow for DV components to not get the default theme all the time.

### CODE REVIEW

**Review by kdinev — APPROVED** [review]

**Comment by HristoP96** [comment]
This PR should be merged after this one #268

**Review by HristoP96 — CHANGES_REQUESTED** [review]
This PR should be merged after fixing this issue #268

**Comment by HristoP96** [comment]
Actually I just saw that this change was merged into vnext so this [PR](https://github.com/IgniteUI/igniteui-docfx-template/pull/269) will apply the change to mastre

**Comment by HristoP96** [comment]
The fix is applied in this [PR](https://github.com/IgniteUI/igniteui-docfx-template/pull/269)

**Pull request closed without merging**
