### PR TITLE
Enable codesandbox live editing button

### PR DESCRIPTION
**Pull request by dobromirts**
Closes #https://github.com/IgniteUI/igniteui-docfx-template/issues/442

### CODE REVIEW

**Comment by dobromirts** [comment]
Steps to test this PR:

1. Build the project 'npm run build:dev'
2. Open the docfx project https://github.com/IgniteUI/igniteui-docfx and link the template in it - npm link igniteui-docfx-template. Execute 'npm run start'
3. Run samples from this repo https://github.com/IgniteUI/igniteui-angular-samples
In order to be able to test locally all type of samples two different commands are used;
 - npm run start:live-editing 
 - npm run start:app-crm:live-editing
 When this script is executed in the samples project it will be load on port 4200.
Check codesandbox and stackblitz for the loaded samples loaded in the code views part of loaded 'docfx' project loaded on port 3000.
When testing the samples with 'npm run start:app-crm:live-editing' change this code in the template project in angular-code-service file line 140.
` 
      if (util.isLocalhost) {
            demoPath = demoPath.replace(projectPath, 'angular-demos');
        }
` 
to 
`
        if (util.isLocalhost) {
            demoPath = demoPath.replace(projectPath, 'angular-lob');
        }
`
4. In order to test DV sample like gaugages, charts etc. clone this repository https://github.com/IgniteUI/igniteui-angular-examples/tree/master. Open 'browser' folder and do npm install. When the command is completed start the project 'npm run start'. Note currently testing is available only for master branch due to the thrown errors when trying to start this project from vnext branch.
5. Check codesandbox for DV samples for the samples provided in the project from step 4

**Comment by hanastasov** [comment]
Opening the Grid clipboard operations sample in CodeSandbox results in:

image

**Comment by hanastasov** [comment]
igniteui-angular-examples repo generates two different [aths, when run from vnext or master:

master => http://localhost:4200/samples/charts/pie-chart/overview
vnext => http://localhost:4200/charts/pie-chart/overview

Let's check if this needs some handling.

**Comment by dobromirts** [comment]
> igniteui-angular-examples repo generates two different [aths, when run from vnext or master:
> 
> master => http://localhost:4200/samples/charts/pie-chart/overview vnext => http://localhost:4200/charts/pie-chart/overview
> 
> Let's check if this needs some handling.

Currently the hosted version for master and staging are following the same structure https://staging.infragistics.com/angular-demos-dv/charts/doughnut-chart/legend . I think that there should be additional changes added for the vnext branch in order to run the project properly and without any errors.

**Comment by hanastasov** [comment]
> 

If somehow the structure is the same whern deployed on staging/prod environments, this PR will be merged in order to test the story on staging.

**Review by hanastasov — CHANGES_REQUESTED** [review]

**Comment by dobromirts** [comment]
Should be tested after stackblitz node starter environment is fixed. https://stackblitz.com/edit/stackblitz-starters-dp8zf8?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js&title=node.new%20Starter
image

**Comment by dobromirts** [comment]
> Should be tested after stackblitz node starter environment is fixed. https://stackblitz.com/edit/stackblitz-starters-dp8zf8?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js&title=node.new%20Starter image

Resolved.

**Pull request merged**
