### PR TITLE
added a button with a link to github repo for samples

### PR DESCRIPTION
**Pull request by HUSSAR-mtrela**
per request from Jason

image

### CODE REVIEW

**Comment by HUSSAR-mtrela** [comment]
@zdrawku  why did you mark this PR with do-not-merge label?

**Comment by HUSSAR-mtrela** [comment]
@zdrawku can you tell me why this PR is marked do-not-merged for almost 1 year now without an explanation?

**Comment by zdrawku** [comment]
This type of change proposal should go through a Design implementation first. We have a stict design for the code view section of the samples that cannot be altered based on some request without explanation. 

Please go ahead and log a feature request that explains in more details the incentives behind the change (even if they are obvious), **as we have a process of implementing/reviewing things that should be tracked and prioritized**. 

Then we can ask for a design that will comply with the initial design, example would be, the bottom area with action buttons is meant for editor (like stavkbliz and codesandbox) and the top right area is meant for cross-reference like `open the full screen app` or `open github sample location`.

image

**Comment by zdrawku** [comment]
Closing for the time being as there are no plans to expose such a button from a Design perspective, we can re-evaluate in the future

**Pull request closed without merging**
